<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Dell-PC" name="com.flipkart.qa.testcases.LoginTest_GroupingTestcase" tests="6" failures="1" timestamp="25 Sep 2018 15:07:41 GMT" time="158.030" errors="0">
  <testcase name="loginTest" time="26.263" classname="com.flipkart.qa.testcases.LoginTest_GroupingTestcase"/>
  <testcase name="MobilesTest" time="24.284" classname="com.flipkart.qa.testcases.LoginTest_GroupingTestcase"/>
  <testcase name="WomenfasionTest" time="26.310" classname="com.flipkart.qa.testcases.LoginTest_GroupingTestcase"/>
  <testcase name="MenfasionTest" time="28.354" classname="com.flipkart.qa.testcases.LoginTest_GroupingTestcase"/>
  <testcase name="TitleValitationTest" time="24.124" classname="com.flipkart.qa.testcases.LoginTest_GroupingTestcase">
    <failure type="java.lang.AssertionError" message="expected [Online Shopping Site for Mobiles, Fashion, Books, Electronics, Home Appliances and More] but found [Online Shopping Site for Mobiles, Electronics, Furniture, Grocery, Lifestyle, Books &amp; More. Exclusive Offers!]">
      <![CDATA[java.lang.AssertionError: expected [Online Shopping Site for Mobiles, Fashion, Books, Electronics, Home Appliances and More] but found [Online Shopping Site for Mobiles, Electronics, Furniture, Grocery, Lifestyle, Books & More. Exclusive Offers!]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.flipkart.qa.testcases.LoginTest_GroupingTestcase.TitleValitationTest(LoginTest_GroupingTestcase.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TitleValitationTest -->
  <testcase name="LogoValidationTest" time="28.695" classname="com.flipkart.qa.testcases.LoginTest_GroupingTestcase"/>
</testsuite> <!-- com.flipkart.qa.testcases.LoginTest_GroupingTestcase -->
